# Generated by Django 4.0.4 on 2022-05-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
