# Generated by Django 4.0.4 on 2022-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=True, max_length=255, unique=True),
        ),
    ]
