# Generated by Django 4.0.4 on 2022-05-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.TextField(default=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
