# Generated by Django 4.0.4 on 2022-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=True, max_length=10000, primary_key=True, serialize=False, unique=True),
        ),
    ]
