# Generated by Django 4.0.4 on 2022-04-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_city_id_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
