# Generated by Django 4.0.4 on 2022-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_remove_city_id_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_id',
            field=models.IntegerField(default=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
