# Generated by Django 4.0.4 on 2022-04-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_city_city_id_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
